### ISSUE TITLE
Clarification on the paper

### ISSUE THREAD

**Issue by kennyvoo** [Titor99/SC-ReID#1]
Hello, great work! I hope to clarify a few questions.

Are the following the only differences between SC-ReID and FaceCC during training?

| Header | FaceCC | SC-Reid |
|--------|--------|--------|
| Model | PCB+MobileFaceNet (for face) | HRNet18 + HRNet18 (for head)|
| Dataset | Filter out data with facial images fewer than 500 pixels  | Full dataset since it uses Head images? |

FaceCC is able to achieve impressive r1 of 82.4 on LTCC with CCPRF dataset. Have you tried the training the SC-ReID with the same strategy ?

**Comment by Titor99** [comment]
Thank you for your question! The primary task of the SC-ReID model is to explore the performance of the person re-identification model in scenarios where the person's clothing is the same, rather than focusing on its performance on the LTCC dataset. Therefore, the SC-ReID model does not use the strategies of the FaceCC model.
